BILLING_API_URL = 'https://billing.bizflycloud.vn/api/v4/'

PLAN_RESOURCE_ENDPOINT = 'plans'
PRICING_MODEL_RESOURCE_ENDPOINT = 'pricing_models'
BILLING_MODEL_RESOURCE_ENDPOINT = 'billing_models'
SUBSCRIPTION_RESOURCE_ENDPOINT = 'subscriptions'
ACCOUNT_RESOURCE_ENDPOINT = 'accounts'

OPENSTACK_AUTH_URL = 'https://hn-1.vccloud.vn:5000/v3/auth/tokens'
OPENSTACK_DEFAULT_PROJECT_DOMAIN_NAME = 'default'
OPENSTACK_DEFAULT_USER_DOMAIN_NAME = 'Default'
KEYSTONE_AUTH_PLUGIN = 'password'
