# ORDER
ASC = '-'
DESC = '+'
DEFAULT_SORT = 'id'

# Time
ISO_8601 = '%Y-%m-%dT%H:%M:%S'

# CATEGORY CODE
DEFAULT_CATEGORY_CODE = 'DF'
PREMIUM_CATEGORY_CODE = 'PR'
BASIC_CATEGORY_CODE = 'BS'
ENTERPRISE_CATEGORY_CODE = 'EP'
DEDICATED_CATEGORY_CODE = 'DC'

# REGION NAME
HANOI_REGION = 'HaNoi'
HCM_REGION = 'HoChiMinh'

# SUBSCRIPTION
SUBSCRIBE_ACTION = 'SUBSCRIBE'
UPDATE_ACTION = 'UPDATE'
RENEW_ACTION = 'RENEW'
CLOSE_ACTION = 'CLOSE'
